version: '3'
services:
  learn-docker:
    build: .
    container_name: container-sys
    environment:
      # Apply in container docker
      # Same .env of local 
      - PORT=3000
      - MONGO_IP=mongo
      - MONGO_PORT=27017
      - MONGO_USER=haison
      - MONGO_PASSWORD=bokute22102000
    ports:
      - 3000:3000
    networks:
      - connectdb
    depends_on:
      # Ensure service initialized order
      # Service inside "depends-on" have been initialized first
      # Because "learn-docker" depends on "mongo" so that "mongo" will be initialized before "learn-docker" 
      - mongo
  mongo:
    image: mongo
    container_name: container_mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=haison
      - MONGO_INITDB_ROOT_PASSWORD=bokute22102000
    volumes:
      - /mongo-db:/data/db
    networks:
      - connectdb
# Volumes not bind mount and amonymous
volumes:
  mongo-db:
networks:
  connectdb:
