version: '3'
services:
  nginx:
    ports:
      - "3000:80"
  learn-docker:
    build:
      context: .
      args:
        - NODE_ENV=development
    container_name: container-sys
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev
    # env_file:
    #   - ./.env

    # networks:
