version: '3'
services:
  learn-docker:
    build: ./
    container_name: container-test
    environment:
      - PORT=3000
    volumes:
      - ./:/app
      - /app/node_modules
    # env_file:
    #   - ./.env

    # networks:
